### PR TITLE
DBAAS-738: Importing AWS RDS Provider Account failed

### PR DESCRIPTION
**Pull request by xieshenzh**
1. Changed the specsynced condition for UI
2. Check if the AWS service account can be used to read the db instances from AWS before using the credentials to run the RDS controller 
3. Make the inventory ready when it is still importing the db instances 
4. Add `jdbc-url` to connection configmap to support spring service binding for Oracle and SqlServer

### CODE REVIEW

**Comment by jianrongzhang89** [comment]
@xieshenzh can you clarify what you meant here and why it should be done this way: "Make the inventory ready when it is still importing the db instances"?

**Comment by xieshenzh** [comment]
> @xieshenzh can you clarify what you meant here and why it should be done this way: "Make the inventory ready when it is still importing the db instances"?

Because the db instances that are being imported are not ready for binding. They will appear as not available in the inventory status. In this case, make the inventory to be ready while it is still loading the db instances, so that the UI can stop waiting.

**Comment by jianrongzhang89** [comment]
> 

How would this impact the users? It seems confusing if the inventory is ready but the instance is still being imported.

**Comment by xieshenzh** [comment]
> > 
> 
> How would this impact the users? It seems confusing if the inventory is ready but the instance is still being imported.

I don't think there would be any impact. The UI is not expecting any intermediate state from the Inventory, the `specsynced` condition should either be ready or not set. DB instances being loaded is a kind of intermediate state. 
I think the users would be happy to see the Inventory is ready even if some instances are not ready.

**Comment by jianrongzhang89** [comment]
> 

specsynced can also be false if the provider operator runs into error during inventory discovery and the UX would then display the error. I just wanted to make sure this won't impact the UX.   @yzhao583 could you confirm?

**Comment by xieshenzh** [comment]
> > 
> 
> specsynced can also be false if the provider operator runs into error during inventory discovery and the UX would then display the error. I just wanted to make sure this won't impact the UX. @yzhao583 could you confirm?

It will set the condition to false if there is error, but it will set the condition to true when importing database is in progress and error is not happening..

**Comment by yzhao583** [comment]
@xieshenzh @jianrongzhang89 In current implementation, if `SpecSynced` is `false`, UI displays the error msg. If `SpecSynced` is `True`, and there is no instance in the inventory, UI displays the empty state which is not error msg

**Comment by jeremyary** [comment]
@yzhao583 @xieshenzh did we work out if there's more change required for this or if we're in agreement on what's being performed? I can't tell by the last comments if the current approach to set SpecSynced==true prior to being finished is a good or bad thing.

**Comment by xieshenzh** [comment]
> @yzhao583 @xieshenzh did we work out if there's more change required for this or if we're in agreement on what's being performed? I can't tell by the last comments if the current approach to set SpecSynced==true prior to being finished is a good or bad thing.

A db instance can only be loaded when it is available, otherwise AWS won't allow modification to it, for example when a db is under maintenance. 
The agreement is if the condition is not set to true or error, then it must not be set at all otherwise the UI won't work. In this case, if some db is not available for loading, users will see an Inventory without `specsynced` condition and not ready, and users will not know the reason why there is no error and it is not ready. I think this is more confusing than users seeing the Inventory is ready but some db instance are not available and not usable.

**Comment by yzhao583** [comment]
@xieshenzh @jeremyary If inventory is ready, but instance not ready, maybe we can set `SpecSynced` to `True`, but there is no db instance in the response? In this case, UI shows a empty state, not error state.

**Pull request merged**
