### PR TITLE
DBAAS-1186: upgrade to RDS controller v0.1.3

### PR DESCRIPTION
**Pull request by xieshenzh**
Upgrade to RDS controller v0.1.3
Jira: https://issues.redhat.com/browse/DBAAS-1186

### CODE REVIEW

**Review by tchughesiv — DISMISSED** [review]
lgtm but what's the push for the new version?

**Comment by xieshenzh** [comment]
> lgtm but what's the push for the new version?

When the dbaas-operator is uninstalled, the rds-controller will auto-upgrade to the latest version.
In this case, if the dbaas-operator is not compatible with the latest version of rds-controller, users will have to manually uninstall the rds-controller before re-installing the dbaas-operator in the cluster.
I just try to avoid this situation by keeping the rds-controller dependency up to date. 

Currently, openshift is on rds-controller v0.1.1, but kubernetes operatorhub has rds-controller v0.1.3, but I am not sure when openshift will upgrade the rds-controller version as well.
Plus, there is really nothing changed between v0.1.1 and v0.1.3, except some documentation changes. So I think it is safe to upgrade to v0.1.3.

**Comment by jianrongzhang89** [comment]
> > lgtm but what's the push for the new version?
> 
> When the dbaas-operator is uninstalled, the rds-controller will auto-upgrade to the latest version. In this case, if the dbaas-operator is not compatible with the latest version of rds-controller, users will have to manually uninstall the rds-controller before re-installing the dbaas-operator in the cluster. I just try to avoid this situation by keeping the rds-controller dependency up to date.
> 
> Currently, openshift is on rds-controller v0.1.1, but kubernetes operatorhub has rds-controller v0.1.3, but I am not sure when openshift will upgrade the rds-controller version as well. Plus, there is really nothing changed between v0.1.1 and v0.1.3, except some documentation changes. So I think it is safe to upgrade to v0.1.3.

Does this mean we will need to upgrade dbaas operator whenever a newer version of rds-controller becomes available?

**Comment by xieshenzh** [comment]
> Does this mean we will need to upgrade dbaas operator whenever a newer version of rds-controller becomes available?

No, users can manually uninstall the rds-controller before re-installing the dbaas-operator in the cluster.

I am not sure if the aws operators and apis always keep backward compatibility. There were breaking changes around version v0.1.0. No big change after v0.1.1 though. It is better to keep the rds-controller up to date.

**Review by jianrongzhang89 — APPROVED** [review]
LGTM

**Pull request merged**
